### ISSUE TITLE
Issue with spinal casing when using NSwag

### ISSUE THREAD

**Issue by cwoolum** [NJsonSchema/NJsonSchema#40]
My urls use spinal casing but when a method is generated in my typescript, ConvertToLowerStartIdentifier and ConvertToUpperStartIdentifier in GeneratorBase only take spaces into consideration. It should replaces dashes with underscores or camel case the value since dashes would break the typescript. 

I'm not sure if this belongs here or as an override in ClientGeneratorBase in NSwag.

**Comment by rsuter** [comment]
The problem here is that we declare interfaces, and thus we cannot just rename the fields because then the interface would not match the actual data. The fix would be to use quotes as shown here: http://stackoverflow.com/questions/13661144/typescripts-hashtables-and-keys-with-a-dash

The only way to fix this is to also allow to generate classes instead of interfaces and copy the data into new instances of the classes when HTTP data is received. But this is a bigger update...

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/1ccec959e9cceb52b81eb8d9167289490e7fa03f

**Comment by rsuter** [comment]
Added issue: https://github.com/NJsonSchema/NJsonSchema/issues/43
